name: armor
version: 0.1
main: me.rdlo.armor
description: a recreation of The Armor SMP plugin
author: rdlo
api-version: '1.20'
permissions:
  permission.node:
    description: "Op Permission"
    default: op
commands:
  setArmorRank:
    description: "Set a Player's Armor Rank"
    permission: permission.node